[package]
name = "autoclick"
version = "0.1.0"
edition = "2021"

[dependencies]
# https://github.com/Narsil/rdev
rdev = "*"
# https://github.com/rust-sysbar/rust-sysbar/blob/master/examples/simple.rs
sysbar = "*"
